{% set name = "xformers" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xformers-{{ version }}.tar.gz
  sha256: de08cc5844038cc0f13b48cc95d0029863b9aa578c496c2f49b0c882ff9f5901

build:
  number: 1
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                # [cuda_compiler_version == "None"]
  skip: true  # [win]
  skip: true  # [cuda_compiler_version == "10.2"]
  skip: true  # [cuda_compiler_version == "11.0"]
  skip: true  # [cuda_compiler_version == "11.1"]
  rpaths:
    - lib/
    # conda-forge::pytorch provides these libs
    - {{ SP_DIR }}/torch/lib/

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - pytorch =*=cuda*  # [cuda_compiler_version != "None"]
    - pytorch =*=cpu*   # [cuda_compiler_version == "None"]
    - pytorch >=1.12
    - pip
  run:
    - python
    - numpy
    - pyre-extensions ==0.0.29
    - pytorch =*=cuda*  # [cuda_compiler_version != "None"]
    - pytorch =*=cpu*   # [cuda_compiler_version == "None"]

test:
  imports:
    - xformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://facebookresearch.github.io/xformers/
  summary: 'XFormers: A collection of composable Transformer building blocks.'
  license: BSD-3-Clause AND APACHE-2.0
  license_file:
   - LICENSE
   - third_party/cutlass/LICENSE.txt
   - third_party/flash-attention/LICENSE
   - third_party/sputnik/LICENSE
extra:
  recipe-maintainers:
    - jan-janssen
